### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by QuentinPerez**

### CODE REVIEW

**Comment by mpl** [comment]
The results look wrong. The two first links seem to point at http://camlistore.org now, which is probably not what we want. I'll have a closer look later if you want.

**Comment by moul** [comment]
Hi @mpl,

Yes, we updated the different README.md of our projects to match our new image building system with multiarch support
If it does not look ideal for you, we are fully open to your advices, we just want to keep the "hack" section smaller now, so we can concentrate on documenting image building system in a unique repository. The rest of the README.md is all about the image itself (for end-users or forkers).

**Comment by mpl** [comment]
Hi @moul 

yes, I understand the motivation. I'm just saying the patch might have a link/tag mistake that gives a result which is probably not even what _you_ guys wanted. For example, the link on "Launch your Camlistore app on Scaleway servers in minutes." leads to camlistore.org , and I'm thinking you meant for it to lead to https://www.scaleway.com/imagehub/camlistore/ instead.

Anyway, yes, I'll have a go at it later.

**Comment by QuentinPerez** [comment]
Hi @mpl,

Thank for your feedback, sorry I added a title and fixed the link  😃

**Pull request merged**
